export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const NEXT_PAGE = 'NEXT_PAGE';
export const PREV_PAGE = 'PREV_PAGE';

export const GET_RECEIPTS_SUCCESS="GET_RECEIPTS_SUCCESS";
export const ACCEPT_RECEIPT_REQUEST="ACCEPT_RECEIPT_REQUEST";
export const ACCEPT_RECEIPT_CLOSE="ACCEPT_RECEIPT_CLOSE";
export const ACCEPT_RECEIPT_CONFIRM="ACCEPT_RECEIPT_CONFIRM";
export const REJECT_RECEIPT_REQUEST="REJECT_RECEIPT_REQUEST";
export const REJECT_RECEIPT_CLOSE="REJECT_RECEIPT_CLOSE";
export const REJECT_RECEIPT_CONFIRM="REJECT_RECEIPT_CONFIRM";
export const RECEIPT_DETAILS="RECEIPT_DETAILS";
export const RECEIPT_DETAIL_CLOSE="RECEIPT_DETAIL_CLOSE";
export const RECEIPT_SHOW_PENDING="RECEIPT_SHOW_PENDING";
export const RECEIPT_SHOW_REJECTED="RECEIPT_SHOW_REJECTED";
export const RECEIPT_SHOW_ACCEPTED="RECEIPT_SHOW_ACCEPTED";
