export const LOGIN_FAILED="LOGIN_FAILED";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGOUT="LOGOUT";

export const GET_RECEIPTS_SUCCESS="GET_RECEIPTS_SUCCESS";
export const ACCEPT_RECEIPT_REQUEST="ACCEPT_RECEIPT_REQUEST";
export const ACCEPT_RECEIPT_CLOSE="ACCEPT_RECEIPT_CLOSE";
export const ACCEPT_RECEIPT_CONFIRM="ACCEPT_RECEIPT_CONFIRM";
export const REJECT_RECEIPT_REQUEST="REJECT_RECEIPT_REQUEST";
export const REJECT_RECEIPT_CLOSE="REJECT_RECEIPT_CLOSE";
export const REJECT_RECEIPT_CONFIRM="REJECT_RECEIPT_CONFIRM";
